//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dobavljac_robe> Dobavljac_robe { get; set; }
        public virtual DbSet<Dostava> Dostavas { get; set; }
        public virtual DbSet<Dostavljac> Dostavljacs { get; set; }
        public virtual DbSet<Hipermarket> Hipermarkets { get; set; }
        public virtual DbSet<Jelo> Jeloes { get; set; }
        public virtual DbSet<Konobar> Konobars { get; set; }
        public virtual DbSet<Kuvar> Kuvars { get; set; }
        public virtual DbSet<Menadzer> Menadzers { get; set; }
        public virtual DbSet<Meni> Menis { get; set; }
        public virtual DbSet<Nalazi_se> Nalazi_se { get; set; }
        public virtual DbSet<Pice> Pices { get; set; }
        public virtual DbSet<Porudzbina> Porudzbinas { get; set; }
        public virtual DbSet<Restoran> Restorans { get; set; }
        public virtual DbSet<Sastojak> Sastojaks { get; set; }
        public virtual DbSet<Stavka_menija> Stavka_menija { get; set; }
        public virtual DbSet<Zaposleni> Zaposlenis { get; set; }
    
        public virtual int NajprodavanijeJelo(string konId, ObjectParameter ime, ObjectParameter prz, ObjectParameter nazNajprodavanijeg, ObjectParameter kolNajprodavanijeg)
        {
            var konIdParameter = konId != null ?
                new ObjectParameter("konId", konId) :
                new ObjectParameter("konId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NajprodavanijeJelo", konIdParameter, ime, prz, nazNajprodavanijeg, kolNajprodavanijeg);
        }
    }
}
