//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostava
    {
        public string ID { get; set; }
        public string ADR { get; set; }
        public int BR_STANA { get; set; }
        public int Dostavljac_MBR { get; set; }
    
        public virtual Dostavljac Dostavljac { get; set; }
        public virtual Porudzbina Porudzbina { get; set; }
    }
}
