//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Jelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jelo()
        {
            this.Sastojaks = new HashSet<Sastojak>();
            this.Kuvars = new HashSet<Kuvar>();
        }

        [DataMember]
        public string ID { get; set; }
        [DataMember]
        public decimal VEL { get; set; }
        [DataMember]
        public bool POSNO { get; set; }
        [DataMember]
        public int TIP { get; set; }

        [DataMember]
        public virtual Stavka_menija Stavka_menija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [DataMember]
        public virtual ICollection<Sastojak> Sastojaks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kuvar> Kuvars { get; set; }
    }
}
