//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pice
    {
        public string ID { get; set; }
        public decimal ZAP { get; set; }
        public bool ALKOHOLNO { get; set; }
    
        public virtual Stavka_menija Stavka_menija { get; set; }
    }
}
