//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Porudzbina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Porudzbina()
        {
            this.Nalazi_se = new HashSet<Nalazi_se>();
        }

        [DataMember]
        public string ID { get; set; }
        [DataMember]
        public System.DateTime DAT { get; set; }
        [DataMember]
        public int Konobar_MBR { get; set; }
    
        public virtual Dostava Dostava { get; set; }
        
        public virtual Konobar Konobar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nalazi_se> Nalazi_se { get; set; }
    }
}
