//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Stavka_menija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stavka_menija()
        {
            this.Nalazi_se = new HashSet<Nalazi_se>();
        }

        [DataMember]
        public string ID { get; set; }
        [DataMember]
        public string NAZ { get; set; }
        [DataMember]
        public decimal CENA { get; set; }
        [DataMember]
        public Nullable<int> Meni_ID { get; set; }

        [DataMember]
        public virtual Jelo Jelo { get; set; }
        public virtual Meni Meni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nalazi_se> Nalazi_se { get; set; }
        [DataMember]
        public virtual Pice Pice { get; set; }
    }
}
