//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaposleni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zaposleni()
        {
            this.Zaposleni1 = new HashSet<Zaposleni>();
        }
    
        public int MBR { get; set; }
        public System.DateTime DAT { get; set; }
        public string IME { get; set; }
        public string PRZ { get; set; }
        public string TEL { get; set; }
        public decimal PLT { get; set; }
        public Nullable<int> Restoran_ID { get; set; }
        public Nullable<int> Zaposleni_MBR { get; set; }
    
        public virtual Dostavljac Dostavljac { get; set; }
        public virtual Konobar Konobar { get; set; }
        public virtual Kuvar Kuvar { get; set; }
        public virtual Menadzer Menadzer { get; set; }
        public virtual Restoran Restoran { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaposleni> Zaposleni1 { get; set; }
        public virtual Zaposleni Zaposleni2 { get; set; }
    }
}
