CREATE
  TABLE Restoran
  (
    ID   INTEGER NOT NULL IDENTITY(1,1) ,
    NAZ  VARCHAR (100) NOT NULL ,
    ADR  VARCHAR (150) NOT NULL ,
    TEL  VARCHAR (50) NOT NULL ,
    GRAD VARCHAR (100) NOT NULL ,
	VLASNIK VARCHAR (70) NOT NULL 
  )
  ON "default"
GO
